<?php
/**
 * StackingRules
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * StackingRules Class Doc Comment
 *
 * @description Defines stacking rules for redeemables. Read more in the [Help Center](https://support.voucherify.io/article/604-stacking-rules)
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class StackingRules implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'StackingRules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'redeemables_limit' => 'int',
        'applicable_redeemables_limit' => 'int',
        'applicable_redeemables_per_category_limit' => 'int',
        'applicable_exclusive_redeemables_limit' => 'int',
        'applicable_exclusive_redeemables_per_category_limit' => 'int',
        'exclusive_categories' => 'string[]',
        'joint_categories' => 'string[]',
        'redeemables_application_mode' => 'string',
        'redeemables_sorting_rule' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'redeemables_limit' => null,
        'applicable_redeemables_limit' => null,
        'applicable_redeemables_per_category_limit' => null,
        'applicable_exclusive_redeemables_limit' => null,
        'applicable_exclusive_redeemables_per_category_limit' => null,
        'exclusive_categories' => null,
        'joint_categories' => null,
        'redeemables_application_mode' => null,
        'redeemables_sorting_rule' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'redeemables_limit' => true,
        'applicable_redeemables_limit' => true,
        'applicable_redeemables_per_category_limit' => true,
        'applicable_exclusive_redeemables_limit' => true,
        'applicable_exclusive_redeemables_per_category_limit' => true,
        'exclusive_categories' => true,
        'joint_categories' => true,
        'redeemables_application_mode' => true,
        'redeemables_sorting_rule' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'redeemables_limit' => 'redeemables_limit',
        'applicable_redeemables_limit' => 'applicable_redeemables_limit',
        'applicable_redeemables_per_category_limit' => 'applicable_redeemables_per_category_limit',
        'applicable_exclusive_redeemables_limit' => 'applicable_exclusive_redeemables_limit',
        'applicable_exclusive_redeemables_per_category_limit' => 'applicable_exclusive_redeemables_per_category_limit',
        'exclusive_categories' => 'exclusive_categories',
        'joint_categories' => 'joint_categories',
        'redeemables_application_mode' => 'redeemables_application_mode',
        'redeemables_sorting_rule' => 'redeemables_sorting_rule'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'redeemables_limit' => 'setRedeemablesLimit',
        'applicable_redeemables_limit' => 'setApplicableRedeemablesLimit',
        'applicable_redeemables_per_category_limit' => 'setApplicableRedeemablesPerCategoryLimit',
        'applicable_exclusive_redeemables_limit' => 'setApplicableExclusiveRedeemablesLimit',
        'applicable_exclusive_redeemables_per_category_limit' => 'setApplicableExclusiveRedeemablesPerCategoryLimit',
        'exclusive_categories' => 'setExclusiveCategories',
        'joint_categories' => 'setJointCategories',
        'redeemables_application_mode' => 'setRedeemablesApplicationMode',
        'redeemables_sorting_rule' => 'setRedeemablesSortingRule'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'redeemables_limit' => 'getRedeemablesLimit',
        'applicable_redeemables_limit' => 'getApplicableRedeemablesLimit',
        'applicable_redeemables_per_category_limit' => 'getApplicableRedeemablesPerCategoryLimit',
        'applicable_exclusive_redeemables_limit' => 'getApplicableExclusiveRedeemablesLimit',
        'applicable_exclusive_redeemables_per_category_limit' => 'getApplicableExclusiveRedeemablesPerCategoryLimit',
        'exclusive_categories' => 'getExclusiveCategories',
        'joint_categories' => 'getJointCategories',
        'redeemables_application_mode' => 'getRedeemablesApplicationMode',
        'redeemables_sorting_rule' => 'getRedeemablesSortingRule'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const REDEEMABLES_APPLICATION_MODE_ALL = 'ALL';
    public const REDEEMABLES_APPLICATION_MODE_PARTIAL = 'PARTIAL';
    public const REDEEMABLES_SORTING_RULE_CATEGORY_HIERARCHY = 'CATEGORY_HIERARCHY';
    public const REDEEMABLES_SORTING_RULE_REQUESTED_ORDER = 'REQUESTED_ORDER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRedeemablesApplicationModeAllowableValues()
    {
        return [
            self::REDEEMABLES_APPLICATION_MODE_ALL,
            self::REDEEMABLES_APPLICATION_MODE_PARTIAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRedeemablesSortingRuleAllowableValues()
    {
        return [
            self::REDEEMABLES_SORTING_RULE_CATEGORY_HIERARCHY,
            self::REDEEMABLES_SORTING_RULE_REQUESTED_ORDER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('redeemables_limit', $data ?? [], 30);
        $this->setIfExists('applicable_redeemables_limit', $data ?? [], 5);
        $this->setIfExists('applicable_redeemables_per_category_limit', $data ?? [], 1);
        $this->setIfExists('applicable_exclusive_redeemables_limit', $data ?? [], 1);
        $this->setIfExists('applicable_exclusive_redeemables_per_category_limit', $data ?? [], 1);
        $this->setIfExists('exclusive_categories', $data ?? [], [[]]);
        $this->setIfExists('joint_categories', $data ?? [], [[]]);
        $this->setIfExists('redeemables_application_mode', $data ?? [], null);
        $this->setIfExists('redeemables_sorting_rule', $data ?? [], 'REQUESTED_ORDER');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['redeemables_limit']) && ($this->container['redeemables_limit'] > 30)) {
            $invalidProperties[] = "invalid value for 'redeemables_limit', must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['redeemables_limit']) && ($this->container['redeemables_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'redeemables_limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['applicable_redeemables_limit']) && ($this->container['applicable_redeemables_limit'] > 30)) {
            $invalidProperties[] = "invalid value for 'applicable_redeemables_limit', must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['applicable_redeemables_limit']) && ($this->container['applicable_redeemables_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'applicable_redeemables_limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['applicable_redeemables_per_category_limit']) && ($this->container['applicable_redeemables_per_category_limit'] > 5)) {
            $invalidProperties[] = "invalid value for 'applicable_redeemables_per_category_limit', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['applicable_redeemables_per_category_limit']) && ($this->container['applicable_redeemables_per_category_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'applicable_redeemables_per_category_limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['applicable_exclusive_redeemables_limit']) && ($this->container['applicable_exclusive_redeemables_limit'] > 5)) {
            $invalidProperties[] = "invalid value for 'applicable_exclusive_redeemables_limit', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['applicable_exclusive_redeemables_limit']) && ($this->container['applicable_exclusive_redeemables_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'applicable_exclusive_redeemables_limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['applicable_exclusive_redeemables_per_category_limit']) && ($this->container['applicable_exclusive_redeemables_per_category_limit'] > 5)) {
            $invalidProperties[] = "invalid value for 'applicable_exclusive_redeemables_per_category_limit', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['applicable_exclusive_redeemables_per_category_limit']) && ($this->container['applicable_exclusive_redeemables_per_category_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'applicable_exclusive_redeemables_per_category_limit', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getRedeemablesApplicationModeAllowableValues();
        if (!is_null($this->container['redeemables_application_mode']) && !in_array($this->container['redeemables_application_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'redeemables_application_mode', must be one of '%s'",
                $this->container['redeemables_application_mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRedeemablesSortingRuleAllowableValues();
        if (!is_null($this->container['redeemables_sorting_rule']) && !in_array($this->container['redeemables_sorting_rule'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'redeemables_sorting_rule', must be one of '%s'",
                $this->container['redeemables_sorting_rule'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets redeemables_limit
     *
     * @return int|null
     */
    public function getRedeemablesLimit(): ?int
    {
        return $this->container['redeemables_limit'];
    }

    /**
     * Sets redeemables_limit
     *
     * @param int|null $redeemables_limit Defines how many redeemables can be sent in one stacking request (note: more redeemables means more processing time!).
     *
     * @return $this
     */
    public function setRedeemablesLimit(?int $redeemables_limit): static
    {
        if (is_null($redeemables_limit)) {
            array_push($this->openAPINullablesSetToNull, 'redeemables_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeemables_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($redeemables_limit) && ($redeemables_limit > 30)) {
            throw new InvalidArgumentException('invalid value for $redeemables_limit when calling StackingRules., must be smaller than or equal to 30.');
        }
        if (!is_null($redeemables_limit) && ($redeemables_limit < 1)) {
            throw new InvalidArgumentException('invalid value for $redeemables_limit when calling StackingRules., must be bigger than or equal to 1.');
        }

        $this->container['redeemables_limit'] = $redeemables_limit;

        return $this;
    }

    /**
     * Gets applicable_redeemables_limit
     *
     * @return int|null
     */
    public function getApplicableRedeemablesLimit(): ?int
    {
        return $this->container['applicable_redeemables_limit'];
    }

    /**
     * Sets applicable_redeemables_limit
     *
     * @param int|null $applicable_redeemables_limit Defines how many of the sent redeemables will be applied to the order. For example, a user can select 30 discounts but only 5 will be applied to the order and the remaining will be labelled as SKIPPED.
     *
     * @return $this
     */
    public function setApplicableRedeemablesLimit(?int $applicable_redeemables_limit): static
    {
        if (is_null($applicable_redeemables_limit)) {
            array_push($this->openAPINullablesSetToNull, 'applicable_redeemables_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('applicable_redeemables_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($applicable_redeemables_limit) && ($applicable_redeemables_limit > 30)) {
            throw new InvalidArgumentException('invalid value for $applicable_redeemables_limit when calling StackingRules., must be smaller than or equal to 30.');
        }
        if (!is_null($applicable_redeemables_limit) && ($applicable_redeemables_limit < 1)) {
            throw new InvalidArgumentException('invalid value for $applicable_redeemables_limit when calling StackingRules., must be bigger than or equal to 1.');
        }

        $this->container['applicable_redeemables_limit'] = $applicable_redeemables_limit;

        return $this;
    }

    /**
     * Gets applicable_redeemables_per_category_limit
     *
     * @return int|null
     */
    public function getApplicableRedeemablesPerCategoryLimit(): ?int
    {
        return $this->container['applicable_redeemables_per_category_limit'];
    }

    /**
     * Sets applicable_redeemables_per_category_limit
     *
     * @param int|null $applicable_redeemables_per_category_limit Defines how many redeemables per category can be applied in one request.
     *
     * @return $this
     */
    public function setApplicableRedeemablesPerCategoryLimit(?int $applicable_redeemables_per_category_limit): static
    {
        if (is_null($applicable_redeemables_per_category_limit)) {
            array_push($this->openAPINullablesSetToNull, 'applicable_redeemables_per_category_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('applicable_redeemables_per_category_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($applicable_redeemables_per_category_limit) && ($applicable_redeemables_per_category_limit > 5)) {
            throw new InvalidArgumentException('invalid value for $applicable_redeemables_per_category_limit when calling StackingRules., must be smaller than or equal to 5.');
        }
        if (!is_null($applicable_redeemables_per_category_limit) && ($applicable_redeemables_per_category_limit < 1)) {
            throw new InvalidArgumentException('invalid value for $applicable_redeemables_per_category_limit when calling StackingRules., must be bigger than or equal to 1.');
        }

        $this->container['applicable_redeemables_per_category_limit'] = $applicable_redeemables_per_category_limit;

        return $this;
    }

    /**
     * Gets applicable_exclusive_redeemables_limit
     *
     * @return int|null
     */
    public function getApplicableExclusiveRedeemablesLimit(): ?int
    {
        return $this->container['applicable_exclusive_redeemables_limit'];
    }

    /**
     * Sets applicable_exclusive_redeemables_limit
     *
     * @param int|null $applicable_exclusive_redeemables_limit Defines how many redeemables with an exclusive category can be applied in one request.
     *
     * @return $this
     */
    public function setApplicableExclusiveRedeemablesLimit(?int $applicable_exclusive_redeemables_limit): static
    {
        if (is_null($applicable_exclusive_redeemables_limit)) {
            array_push($this->openAPINullablesSetToNull, 'applicable_exclusive_redeemables_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('applicable_exclusive_redeemables_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($applicable_exclusive_redeemables_limit) && ($applicable_exclusive_redeemables_limit > 5)) {
            throw new InvalidArgumentException('invalid value for $applicable_exclusive_redeemables_limit when calling StackingRules., must be smaller than or equal to 5.');
        }
        if (!is_null($applicable_exclusive_redeemables_limit) && ($applicable_exclusive_redeemables_limit < 1)) {
            throw new InvalidArgumentException('invalid value for $applicable_exclusive_redeemables_limit when calling StackingRules., must be bigger than or equal to 1.');
        }

        $this->container['applicable_exclusive_redeemables_limit'] = $applicable_exclusive_redeemables_limit;

        return $this;
    }

    /**
     * Gets applicable_exclusive_redeemables_per_category_limit
     *
     * @return int|null
     */
    public function getApplicableExclusiveRedeemablesPerCategoryLimit(): ?int
    {
        return $this->container['applicable_exclusive_redeemables_per_category_limit'];
    }

    /**
     * Sets applicable_exclusive_redeemables_per_category_limit
     *
     * @param int|null $applicable_exclusive_redeemables_per_category_limit Defines how many redeemables with an exclusive category per category in stacking rules can be applied in one request.
     *
     * @return $this
     */
    public function setApplicableExclusiveRedeemablesPerCategoryLimit(?int $applicable_exclusive_redeemables_per_category_limit): static
    {
        if (is_null($applicable_exclusive_redeemables_per_category_limit)) {
            array_push($this->openAPINullablesSetToNull, 'applicable_exclusive_redeemables_per_category_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('applicable_exclusive_redeemables_per_category_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($applicable_exclusive_redeemables_per_category_limit) && ($applicable_exclusive_redeemables_per_category_limit > 5)) {
            throw new InvalidArgumentException('invalid value for $applicable_exclusive_redeemables_per_category_limit when calling StackingRules., must be smaller than or equal to 5.');
        }
        if (!is_null($applicable_exclusive_redeemables_per_category_limit) && ($applicable_exclusive_redeemables_per_category_limit < 1)) {
            throw new InvalidArgumentException('invalid value for $applicable_exclusive_redeemables_per_category_limit when calling StackingRules., must be bigger than or equal to 1.');
        }

        $this->container['applicable_exclusive_redeemables_per_category_limit'] = $applicable_exclusive_redeemables_per_category_limit;

        return $this;
    }

    /**
     * Gets exclusive_categories
     *
     * @return string[]|null
     */
    public function getExclusiveCategories(): ?array
    {
        return $this->container['exclusive_categories'];
    }

    /**
     * Sets exclusive_categories
     *
     * @param string[]|null $exclusive_categories Lists all exclusive categories. A redeemable from a campaign with an exclusive category is the only redeemable to be redeemed when applied with redeemables from other campaigns unless these campaigns are exclusive or joint.
     *
     * @return $this
     */
    public function setExclusiveCategories(?array $exclusive_categories): static
    {
        if (is_null($exclusive_categories)) {
            array_push($this->openAPINullablesSetToNull, 'exclusive_categories');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('exclusive_categories', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['exclusive_categories'] = $exclusive_categories;

        return $this;
    }

    /**
     * Gets joint_categories
     *
     * @return string[]|null
     */
    public function getJointCategories(): ?array
    {
        return $this->container['joint_categories'];
    }

    /**
     * Sets joint_categories
     *
     * @param string[]|null $joint_categories Lists all joint categories. A campaign with a joint category is always applied regardless of the exclusivity of other campaigns.
     *
     * @return $this
     */
    public function setJointCategories(?array $joint_categories): static
    {
        if (is_null($joint_categories)) {
            array_push($this->openAPINullablesSetToNull, 'joint_categories');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('joint_categories', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['joint_categories'] = $joint_categories;

        return $this;
    }

    /**
     * Gets redeemables_application_mode
     *
     * @return string|null
     */
    public function getRedeemablesApplicationMode(): ?string
    {
        return $this->container['redeemables_application_mode'];
    }

    /**
     * Sets redeemables_application_mode
     *
     * @param string|null $redeemables_application_mode Defines redeemables application mode.
     *
     * @return $this
     */
    public function setRedeemablesApplicationMode(?string $redeemables_application_mode): static
    {
        if (is_null($redeemables_application_mode)) {
            array_push($this->openAPINullablesSetToNull, 'redeemables_application_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeemables_application_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getRedeemablesApplicationModeAllowableValues();
        if (!is_null($redeemables_application_mode) && !in_array($redeemables_application_mode, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'redeemables_application_mode', must be one of '%s'",
                    $redeemables_application_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['redeemables_application_mode'] = $redeemables_application_mode;

        return $this;
    }

    /**
     * Gets redeemables_sorting_rule
     *
     * @return string|null
     */
    public function getRedeemablesSortingRule(): ?string
    {
        return $this->container['redeemables_sorting_rule'];
    }

    /**
     * Sets redeemables_sorting_rule
     *
     * @param string|null $redeemables_sorting_rule Defines redeemables sorting rule.
     *
     * @return $this
     */
    public function setRedeemablesSortingRule(?string $redeemables_sorting_rule): static
    {
        if (is_null($redeemables_sorting_rule)) {
            array_push($this->openAPINullablesSetToNull, 'redeemables_sorting_rule');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeemables_sorting_rule', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getRedeemablesSortingRuleAllowableValues();
        if (!is_null($redeemables_sorting_rule) && !in_array($redeemables_sorting_rule, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'redeemables_sorting_rule', must be one of '%s'",
                    $redeemables_sorting_rule,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['redeemables_sorting_rule'] = $redeemables_sorting_rule;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


